In [2]:
import numpy as np # Create a numpy array with elements 1, 2, and 3
np.array([1,2,3]) # array([1, 2, 3]) it creates a numpy array with the specified elements


array([1, 2, 3])

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1) #it will return <class 'numpy.ndarray'> indicating that arr1 is a numpy array

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]]) #np.array creates a 2D numpy array (matrix) with two rows and three columns
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3 = np.zeros((2,3)) #np.zeros creates a 2D numpy array (matrix) with two rows and three columns filled with zeros
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4 = np.ones((3,4)) #np.ones creates a 2D numpy array (matrix) with three rows and four columns filled with ones
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr5 = np.identity(5) #np.identity creates a 2D identity matrix of size 5x5
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
arr6 = np.arange(10) #np.arange creates a 1D numpy array with values ranging from 0 to 9
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr7 = np.arange(5,16,2) #np.arange creates a 1D numpy array with values starting from 5 to 15 with a step of 2
arr7

array([ 5,  7,  9, 11, 13, 15])

In [14]:
arr8 = np.linspace(10,20,5) #np.linspace creates a 1D numpy array with 5 evenly spaced values between 10 and 20
arr8

array([10. , 12.5, 15. , 17.5, 20. ])

In [15]:
arr9 = arr7.copy() #.copy() creates a copy of the numpy array arr7      
arr9

array([ 5,  7,  9, 11, 13, 15])

SOME IMPORTANT ATTRIBUTES
1. shape
2. nDim
3. size
4. itemsize
5. Dtype
6. astype()

In [16]:
arr2.shape #.shape returns the dimensions of the numpy array arr2 as a tuple (2, 3) indicating 2 rows and 3 columns

(2, 3)

In [17]:
arr10 = np.array([[[1,2],[3,4],[5,6]]]) #3D numpy array with one block, three rows, and two columns
arr10

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
arr10.shape #.shape returns the dimensions of the 3D numpy array arr10 as a tuple (1, 3, 2) indicating 1 block, 3 rows, and 2 columns

(1, 3, 2)

In [19]:
arr10.ndim #.ndim returns the number of dimensions of the numpy array arr10, which is 3 in this case

3

In [20]:
arr1.size

5

In [21]:
arr10.size

6

In [22]:
arr9.itemsize

8

In [23]:
arr10.dtype

dtype('int64')

In [24]:
arr10.astype('float64') #.astype('float64') converts the data type of the numpy array arr10 to float64
arr10

array([[[1, 2],
        [3, 4],
        [5, 6]]])

List vs array
1. faster
2. convenient
3. less memory


In [26]:
lista = range(100) #range(100) generates a sequence of numbers from 0 to 99
arr11 = np.arange(100) #np.range is incorrect, the correct function is np.arange

In [27]:
import sys #import the sys module to access system-specific parameters and functions


In [28]:
print(sys.getsizeof(87)*len(lista)) # Calculate and print the memory size of the Python list 'lista' containing 100 integers

2800


In [29]:
print(arr11.itemsize* arr11.size) # Calculate and print the memory size of the numpy array 'arr11' containing 100 integers

800


In [38]:
import time

In [42]:
x = range(100000000) # Create a range object 'x' containing numbers from 0 to 999999
y = range(100000000,20000000) # Create a range object 'y' containing numbers from 1000000 to 1199999

start_time = time.time() # Record the current time before starting the operation

c = [(x, y ) for x,y in zip(x,y)] # Create a list of tuples by zipping together the elements from 'x' and 'y'

print(time.time() - start_time) # Calculate and print the time taken to execute the list comprehension operation

0.05254411697387695


In [43]:
a = np.arange(100000000) # Create a numpy array 'y' containing numbers from 0 to 999999
b = np.arange(100000000,200000000) # Create a numpy array 'y' containing numbers from 1000000 to 1999999

start_time = time.time() # Record the current time before starting the operation

c = a + b # Perform element-wise addition of numpy arrays 'a' and 'b'

print(time.time() - start_time) # Calculate and print the time taken to execute the numpy array addition operation

0.887554407119751


INDEXING, SLICING AND ITERATION

In [45]:
arr12 = np.arange(24).reshape(6,4) #np.arange(24) creates a 1D numpy array with values from 0 to 23, and .reshape(6,4) reshapes it into a 2D array with 6 rows and 4 columns
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr12[2] # Access the third row of the 2D numpy array arr12

array([ 8,  9, 10, 11])

In [49]:
arr12[:2] # Access the first two rows of the 2D numpy array arr12

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
arr12[:,2] # Access the third column of the 2D numpy array arr12 because the colon (:) before the comma indicates all rows, and the 2 after the comma specifies the third column (indexing starts from 0).

array([ 2,  6, 10, 14, 18, 22])

In [52]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [53]:
arr12[2:4, 1:3] # Access a subarray from the 2D numpy array arr12 that includes rows 2 to 3 (index 2 and 3) and columns 1 to 2 (index 1 and 2).

array([[ 9, 10],
       [13, 14]])

In [54]:
arr12[4:,2:]    # Access a subarray from the 2D numpy array arr12 that includes rows 4 to the end and columns 2 to the end.

array([[18, 19],
       [22, 23]])

In [55]:
for i in arr12:
    print(i) # Iterate through each row of the 2D numpy array arr12 and print it

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [56]:
for i in np.nditer(arr12):
    print(i) # Iterate through each element of the 2D numpy array arr12 and print it


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


NUMPY OPERATION

In [ ]:
import numpy as np 

In [57]:
arr1 = np.array([1, 2, 3,4,5,6])
arr2 = np.array([4, 5, 6,7,8,9])

arr1- arr2

array([-3, -3, -3, -3, -3, -3])

In [58]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [59]:
arr1*2 # Multiply each element of the numpy array arr1 by 2, it is scalar multiplication

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2>3 # Check which elements in the numpy array arr2 are greater than 3, returning a boolean array

array([ True,  True,  True,  True,  True,  True])

In [10]:
import numpy as np

In [13]:
arr3 = np.arange(6).reshape(2,3) # Create a 2D numpy array with 2 rows and 3 columns
arr4 =np.arange(6,12).reshape(3,2) # Create another 2D numpy array with 2 rows and 3 columns


In [14]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [15]:
arr1.dot(arr3)

ValueError: shapes (5,) and (2,3) not aligned: 5 (dim 0) != 2 (dim 0)

In [16]:
arr4.max()

np.int64(11)

In [17]:
arr4.min()

np.int64(6)

In [18]:
arr4.min(axis=0) # Find the minimum values along each column (axis 0) of the 2D numpy array arr4

array([6, 7])

In [19]:
arr4.min(axis=1) # Find the minimum values along each row (axis 1) of the 2D numpy array arr4

array([ 6,  8, 10])

In [20]:
arr4.sum(axis=0) # Calculate the sum of elements along each column (axis 0) of the 2D numpy array arr4

array([24, 27])

In [21]:
arr4.mean(axis=0) # Calculate the mean (average) of elements along each column (axis 0) of the 2D numpy array arr4

array([8., 9.])

In [22]:
arr4.std() # Calculate the standard deviation of all elements in the 2D numpy array arr4

np.float64(1.707825127659933)

In [23]:
np.sin(arr4) # Calculate the sine of each element in the 2D numpy array arr4

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [24]:
np.median(arr4) # Calculate the median of all elements in the 2D numpy array arr4

np.float64(8.5)

In [25]:
np.exp(arr4) # Calculate the exponential (e^x) of each element in the 2D numpy array arr4

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

RESHAPING AN ARRAY
1. Ravel
2. Reshape
3. Transpose
4. Stacking
5. Splitting

In [27]:
import numpy as np

In [28]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
arr4.ndim

2

In [30]:
arr4.ravel() # Flatten the 2D numpy array arr4 into a 1D array


array([ 6,  7,  8,  9, 10, 11])

In [31]:
arr4 

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [32]:
arr4.transpose() # Transpose the 2D numpy array arr4, swapping its rows and columns

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [33]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [42]:
arr5 = np.arange(12,18).reshape(2,3) # Create a 1D numpy array with values from 12 to 17 using the arange function, which generates a sequence of numbers within a specified range.
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [43]:
np.hstack((arr3, arr5)) # Horizontally stack arr3 and arr5 along axis 1 (columns)

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [45]:
np.vstack((arr3, arr4))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [46]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [49]:
np.hsplit(arr3,3) # Split the 2D numpy array arr3 into 2 equal parts along axis 1 (columns)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [50]:
np.vsplit(arr3, 2) # Split the 2D numpy array arr3 into 2 equal parts along axis 0 (rows)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [51]:
import numpy as np

In [54]:
arr8 = np.arange(24).reshape(6,4) 

In [55]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr8[[0,2,4]] # Access the first, third, and fifth rows of the 2D numpy array arr8 using advanced indexing with a list of row indices

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

 NEXT PART INDEXING WITH BOOLEAN ARRAYS