INDEXING WITH BOOLEAN ARRAYS

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low = 1, high = 100, size = 20).reshape(4,5)
arr

array([[67, 55,  8, 40, 21],
       [77, 89, 13, 13, 37],
       [50, 20,  4, 35, 82],
       [64, 72, 39, 32, 89]], dtype=int32)

In [3]:
arr[0]

array([67, 55,  8, 40, 21], dtype=int32)

In [4]:
arr>50

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False,  True],
       [ True,  True, False, False,  True]])

In [5]:
arr[arr>50] #indexing using boolean array

array([67, 55, 77, 89, 82, 64, 72, 89], dtype=int32)

In [6]:
arr[(arr>50) & (arr%2!=0)] #indexing using boolean array with multiple conditions

array([67, 55, 77, 89, 89], dtype=int32)

In [ ]:
arr[(arr>50) & (arr%2!=0)] = 0 #assigning new value to the indexed array
arr

array([[ 0,  0,  8, 40, 21],
       [ 0,  0, 13, 13, 37],
       [50, 20,  4, 35, 82],
       [64, 72, 39, 32,  0]], dtype=int32)